import type {
  User,
  Chat,
  Message,
  Post,
  Comment,
  Story,
  StoryGroup,
  Video,
  Stream,
  Meeting,
  Notification,
  FileItem,
  MediaItem,
} from '@/types'

// ============================================
// Mock Users
// ============================================
export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'jasur_karimov',
    displayName: 'Jasur Karimov',
    email: 'jasur@example.com',
    avatar: undefined,
    bio: 'Software engineer & tech enthusiast. Building the future one line at a time. 🚀',
    status: 'online',
    role: 'premium',
    isVerified: true,
    isPremium: true,
    followers: 12400,
    following: 890,
    postsCount: 342,
    joinedAt: '2024-01-15T10:00:00Z',
    lastSeen: new Date().toISOString(),
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: true },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
    profile: {
      bio: 'Software engineer & tech enthusiast. Building the future one line at a time. 🚀',
      location: 'Tashkent, Uzbekistan',
      website: 'https://jasur.dev',
      birthday: '1995-06-15',
      interests: ['technology', 'photography', 'travel', 'AI'],
      socialLinks: { twitter: 'jasurdev', github: 'jasurkarimov' },
    },
  },
  {
    id: 'u2',
    username: 'dilnoza_rakhimova',
    displayName: 'Dilnoza Rakhimova',
    email: 'dilnoza@example.com',
    avatar: undefined,
    bio: 'UX designer crafting beautiful digital experiences ✨',
    status: 'online',
    role: 'premium',
    isVerified: true,
    isPremium: true,
    followers: 8200,
    following: 456,
    postsCount: 189,
    joinedAt: '2024-02-20T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: false, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: false },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u3',
    username: 'timur_aliyev',
    displayName: 'Timur Aliyev',
    email: 'timur@example.com',
    avatar: undefined,
    bio: 'Full-stack developer | Open source contributor | Coffee lover ☕',
    status: 'away',
    role: 'user',
    isVerified: false,
    isPremium: false,
    followers: 3400,
    following: 678,
    postsCount: 95,
    joinedAt: '2024-03-10T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: false, messagePreview: true, groupNotifications: false, liveNotifications: true },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: false, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u4',
    username: 'nodira_ushakova',
    displayName: 'Nodira Ushakova',
    email: 'nodira@example.com',
    avatar: undefined,
    bio: 'Digital artist & illustrator 🎨 Creating worlds from pixels',
    status: 'online',
    role: 'user',
    isVerified: true,
    isPremium: false,
    followers: 15600,
    following: 312,
    postsCount: 567,
    joinedAt: '2023-11-05T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: true },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u5',
    username: 'alex_chen',
    displayName: 'Alex Chen',
    email: 'alex@example.com',
    avatar: undefined,
    bio: 'Product designer at a fintech startup. Design systems advocate.',
    status: 'offline',
    role: 'user',
    isVerified: false,
    isPremium: true,
    followers: 5200,
    following: 743,
    postsCount: 210,
    joinedAt: '2024-01-30T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: false, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: false },
      privacy: { profileVisibility: 'public', onlineStatus: false, readReceipts: true, typingIndicator: true, lastSeen: false },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u6',
    username: 'sardor_mirzayev',
    displayName: 'Sardor Mirzayev',
    email: 'sardor@example.com',
    avatar: undefined,
    bio: 'Data scientist & ML engineer. Turning data into insights 📊',
    status: 'busy',
    role: 'moderator',
    isVerified: true,
    isPremium: false,
    followers: 9800,
    following: 234,
    postsCount: 156,
    joinedAt: '2023-09-20T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: true },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u7',
    username: 'maria_garcia',
    displayName: 'Maria Garcia',
    email: 'maria@example.com',
    avatar: undefined,
    bio: 'Content creator & lifestyle blogger. Living my best life ✨',
    status: 'online',
    role: 'user',
    isVerified: true,
    isPremium: true,
    followers: 24500,
    following: 567,
    postsCount: 890,
    joinedAt: '2023-06-10T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: true },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u8',
    username: 'bobur_toshmatov',
    displayName: 'Bobur Toshmatov',
    email: 'bobur@example.com',
    avatar: undefined,
    bio: 'Backend engineer | Rust & Go enthusiast | Distributed systems',
    status: 'offline',
    role: 'user',
    isVerified: false,
    isPremium: false,
    followers: 2100,
    following: 890,
    postsCount: 67,
    joinedAt: '2024-04-05T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: false, soundEnabled: true, messagePreview: true, groupNotifications: false, liveNotifications: true },
      privacy: { profileVisibility: 'friends', onlineStatus: true, readReceipts: true, typingIndicator: false, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u9',
    username: 'yuki_tanaka',
    displayName: 'Yuki Tanaka',
    email: 'yuki@example.com',
    avatar: undefined,
    bio: 'iOS developer by day, game dev by night 🎮',
    status: 'online',
    role: 'user',
    isVerified: false,
    isPremium: false,
    followers: 6700,
    following: 445,
    postsCount: 234,
    joinedAt: '2024-02-14T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: true, messagePreview: true, groupNotifications: true, liveNotifications: false },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
  {
    id: 'u10',
    username: 'olivia_smith',
    displayName: 'Olivia Smith',
    email: 'olivia@example.com',
    avatar: undefined,
    bio: 'Marketing manager | Brand strategist | Coffee addict ☕',
    status: 'away',
    role: 'user',
    isVerified: false,
    isPremium: false,
    followers: 4300,
    following: 678,
    postsCount: 145,
    joinedAt: '2024-03-25T10:00:00Z',
    settings: {
      theme: 'dark',
      language: 'en',
      notifications: { pushEnabled: true, emailEnabled: true, soundEnabled: false, messagePreview: true, groupNotifications: true, liveNotifications: false },
      privacy: { profileVisibility: 'public', onlineStatus: true, readReceipts: true, typingIndicator: true, lastSeen: true },
      appearance: { fontSize: 'medium', compactMode: false, animations: true },
    },
  },
]

// ============================================
// Mock Messages
// ============================================
export const mockMessages: Message[] = [
  {
    id: 'm1',
    chatId: 'c1',
    senderId: 'u2',
    content: 'Hey Jasur! Have you seen the new design system updates? They look incredible 🔥',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '🔥', userIds: ['u1'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'm2',
    chatId: 'c1',
    senderId: 'u1',
    content: 'Yes! The glassmorphism approach is exactly what we needed. The dark mode variant is stunning.',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '💯', userIds: ['u2'] }, { emoji: '✨', userIds: ['u2'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'm3',
    chatId: 'c1',
    senderId: 'u2',
    content: 'I also added some micro-interactions with Framer Motion. Want me to share the prototype?',
    type: 'text',
    status: 'read',
    reactions: [],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
  },
  {
    id: 'm4',
    chatId: 'c2',
    senderId: 'u3',
    content: 'The deployment went smoothly. All services are up and running 🚀',
    type: 'text',
    status: 'delivered',
    reactions: [{ emoji: '🎉', userIds: ['u1', 'u6'] }],
    attachments: [],
    mentions: ['u6'],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'm5',
    chatId: 'c2',
    senderId: 'u6',
    content: 'Great work Timur! The API response times are down to 45ms average. Sardor optimized the queries.',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '💪', userIds: ['u3', 'u1'] }],
    attachments: [],
    mentions: ['u3'],
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'm6',
    chatId: 'c2',
    senderId: 'u1',
    content: 'Amazing team effort! Let\'s push the next feature branch tomorrow morning.',
    type: 'text',
    status: 'read',
    reactions: [],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'm7',
    chatId: 'c3',
    senderId: 'u4',
    content: 'Just finished the new illustration set for the onboarding flow! Check it out 🎨',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '😍', userIds: ['u1', 'u2', 'u5'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'm8',
    chatId: 'c3',
    senderId: 'u5',
    content: 'Nodira these are beautiful! The color palette is perfect for our brand.',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '❤️', userIds: ['u4'] }],
    attachments: [],
    mentions: ['u4'],
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
  {
    id: 'm9',
    chatId: 'c4',
    senderId: 'u7',
    content: 'Going live in 10 minutes! Today we\'re discussing the latest web design trends for 2025 🎬',
    type: 'text',
    status: 'delivered',
    reactions: [{ emoji: '🎬', userIds: ['u1', 'u9', 'u10'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'm10',
    chatId: 'c5',
    senderId: 'u9',
    content: 'Just published my first indie game on the App Store! It\'s a puzzle adventure called "Crystal Maze" 🎮',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '🎮', userIds: ['u1'] }, { emoji: '🎉', userIds: ['u3'] }, { emoji: '🏆', userIds: ['u6'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'm11',
    chatId: 'c6',
    senderId: 'u10',
    content: 'The Q4 marketing report is ready for review. Revenue is up 23% from last quarter! 📈',
    type: 'text',
    status: 'delivered',
    reactions: [],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'm12',
    chatId: 'c7',
    senderId: 'u1',
    content: 'Welcome to the Honey Design Community! Feel free to share your work and get feedback 🍯',
    type: 'text',
    status: 'read',
    reactions: [{ emoji: '🍯', userIds: ['u2', 'u3', 'u4', 'u5'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'm13',
    chatId: 'c8',
    senderId: 'u6',
    content: '📢 Weekly ML paper reading session tomorrow at 7PM Tashkent time. This week: Attention Is All You Need revisited.',
    type: 'text',
    status: 'delivered',
    reactions: [{ emoji: '📚', userIds: ['u1', 'u3'] }],
    attachments: [],
    mentions: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
]

// ============================================
// Mock Chats
// ============================================
export const mockChats: Chat[] = [
  {
    id: 'c1',
    type: 'private',
    participants: [
      { userId: 'u1', role: 'member', joinedAt: '2024-01-15T10:00:00Z', isMuted: false },
      { userId: 'u2', role: 'member', joinedAt: '2024-01-15T10:00:00Z', isMuted: false },
    ],
    lastMessage: mockMessages[2],
    unreadCount: 1,
    isPinned: true,
    isMuted: false,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
  },
  {
    id: 'c2',
    type: 'group',
    name: 'Dev Team 🛠️',
    avatar: undefined,
    description: 'Development team coordination',
    participants: [
      { userId: 'u1', role: 'admin', joinedAt: '2024-01-20T10:00:00Z', isMuted: false },
      { userId: 'u3', role: 'member', joinedAt: '2024-01-20T10:00:00Z', isMuted: false },
      { userId: 'u6', role: 'member', joinedAt: '2024-01-20T10:00:00Z', isMuted: false },
      { userId: 'u8', role: 'member', joinedAt: '2024-04-05T10:00:00Z', isMuted: false },
    ],
    admins: ['u1'],
    memberCount: 4,
    lastMessage: mockMessages[5],
    unreadCount: 2,
    isPinned: true,
    isMuted: false,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'c3',
    type: 'group',
    name: 'Design Studio',
    avatar: undefined,
    description: 'Creative discussions and design reviews',
    participants: [
      { userId: 'u2', role: 'admin', joinedAt: '2024-02-01T10:00:00Z', isMuted: false },
      { userId: 'u4', role: 'member', joinedAt: '2024-02-01T10:00:00Z', isMuted: false },
      { userId: 'u5', role: 'member', joinedAt: '2024-02-01T10:00:00Z', isMuted: false },
    ],
    admins: ['u2'],
    memberCount: 3,
    lastMessage: mockMessages[7],
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
  {
    id: 'c4',
    type: 'private',
    participants: [
      { userId: 'u1', role: 'member', joinedAt: '2024-03-01T10:00:00Z', isMuted: false },
      { userId: 'u7', role: 'member', joinedAt: '2024-03-01T10:00:00Z', isMuted: false },
    ],
    lastMessage: mockMessages[8],
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'c5',
    type: 'private',
    participants: [
      { userId: 'u1', role: 'member', joinedAt: '2024-02-14T10:00:00Z', isMuted: false },
      { userId: 'u9', role: 'member', joinedAt: '2024-02-14T10:00:00Z', isMuted: false },
    ],
    lastMessage: mockMessages[9],
    unreadCount: 0,
    isPinned: false,
    isMuted: true,
    createdAt: '2024-02-14T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'c6',
    type: 'private',
    participants: [
      { userId: 'u1', role: 'member', joinedAt: '2024-03-25T10:00:00Z', isMuted: false },
      { userId: 'u10', role: 'member', joinedAt: '2024-03-25T10:00:00Z', isMuted: false },
    ],
    lastMessage: mockMessages[10],
    unreadCount: 1,
    isPinned: false,
    isMuted: false,
    createdAt: '2024-03-25T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'c7',
    type: 'channel',
    name: 'Honey Design Community',
    avatar: undefined,
    description: 'Official design community for Honey platform',
    participants: [
      { userId: 'u1', role: 'owner', joinedAt: '2024-01-10T10:00:00Z', isMuted: false },
      { userId: 'u2', role: 'admin', joinedAt: '2024-01-10T10:00:00Z', isMuted: false },
    ],
    admins: ['u1', 'u2'],
    memberCount: 1240,
    isPrivate: false,
    category: 'Design',
    lastMessage: mockMessages[11],
    unreadCount: 5,
    isPinned: true,
    isMuted: false,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'c8',
    type: 'channel',
    name: 'ML & Data Science',
    avatar: undefined,
    description: 'Machine learning discussions, paper reviews, and AI news',
    participants: [
      { userId: 'u6', role: 'owner', joinedAt: '2024-02-01T10:00:00Z', isMuted: false },
    ],
    admins: ['u6'],
    memberCount: 3200,
    isPrivate: false,
    category: 'Technology',
    lastMessage: mockMessages[12],
    unreadCount: 1,
    isPinned: false,
    isMuted: false,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
]

// ============================================
// Mock Posts
// ============================================
const mockComments: Comment[] = [
  {
    id: 'cm1',
    postId: 'p1',
    authorId: 'u2',
    content: 'This is absolutely gorgeous! The attention to detail is incredible 🔥',
    likes: 12,
    isLiked: false,
    replies: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'cm2',
    postId: 'p1',
    authorId: 'u4',
    content: 'Love the color transitions. Very smooth!',
    likes: 8,
    isLiked: true,
    replies: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'cm3',
    postId: 'p2',
    authorId: 'u3',
    content: 'The golden hour shots are magical. What camera did you use?',
    likes: 5,
    isLiked: false,
    replies: [
      {
        id: 'cm3r1',
        postId: 'p2',
        authorId: 'u7',
        content: 'Canon R5 with a 24-70mm f/2.8 lens! 📸',
        likes: 3,
        isLiked: false,
        replies: [],
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
]

export const mockPosts: Post[] = [
  {
    id: 'p1',
    authorId: 'u4',
    content: 'New illustration series: "Digital Botanics" 🌿✨ Exploring the intersection of nature and technology through digital art. Each piece took about 12 hours to complete.',
    type: 'image',
    visibility: 'public',
    media: [],
    hashtags: ['#DigitalArt', '#Illustration', '#Botanics', '#CreativeProcess'],
    mentions: [],
    likes: 847,
    comments: [mockComments[0], mockComments[1]],
    commentCount: 24,
    shares: 56,
    isLiked: true,
    isShared: false,
    isBookmarked: true,
    isPinned: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'p2',
    authorId: 'u7',
    content: 'Golden hour in Tashkent never disappoints 🌅 The way the light hits the old city walls is something truly magical. #Photography #GoldenHour #Tashkent #Travel',
    type: 'image',
    visibility: 'public',
    media: [],
    hashtags: ['#Photography', '#GoldenHour', '#Tashkent', '#Travel'],
    mentions: [],
    likes: 2340,
    comments: [mockComments[2]],
    commentCount: 89,
    shares: 134,
    isLiked: false,
    isShared: true,
    isBookmarked: false,
    isPinned: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 'p3',
    authorId: 'u1',
    content: 'Just shipped a major update to our design system! Here\'s what\'s new:\n\n✅ Glassmorphism component library\n✅ 50+ new animations\n✅ Dark mode improvements\n✅ Accessibility audit passed\n\nBuilding in public feels great! 🚀',
    type: 'text',
    visibility: 'public',
    media: [],
    hashtags: ['#BuildInPublic', '#DesignSystem', '#OpenSource'],
    mentions: [],
    likes: 456,
    comments: [],
    commentCount: 32,
    shares: 78,
    isLiked: false,
    isShared: false,
    isBookmarked: false,
    isPinned: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'p4',
    authorId: 'u6',
    content: 'Exciting results from our latest ML experiment! Our new model achieved 97.3% accuracy on the benchmark dataset, a 4.2% improvement over the previous state-of-the-art. Paper coming soon! 📊 #MachineLearning #AI',
    type: 'text',
    visibility: 'public',
    media: [],
    hashtags: ['#MachineLearning', '#AI', '#Research', '#DataScience'],
    mentions: [],
    likes: 892,
    comments: [],
    commentCount: 67,
    shares: 156,
    isLiked: true,
    isShared: false,
    isBookmarked: true,
    isPinned: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'p5',
    authorId: 'u5',
    content: 'Redesigned the entire onboarding flow. Conversion rate went from 34% to 58%. The key insight? Less is more. We cut the steps from 7 to 3 and made each one count. #UXDesign #ProductDesign',
    type: 'text',
    visibility: 'public',
    media: [],
    hashtags: ['#UXDesign', '#ProductDesign', '#ConversionOptimization'],
    mentions: [],
    likes: 1203,
    comments: [],
    commentCount: 45,
    shares: 89,
    isLiked: false,
    isShared: false,
    isBookmarked: false,
    isPinned: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
]

// ============================================
// Mock Stories
// ============================================
export const mockStories: StoryGroup[] = [
  {
    userId: 'u2',
    stories: [
      {
        id: 's1',
        authorId: 'u2',
        media: { id: 'sm1', type: 'image', url: '', thumbnailUrl: '', alt: 'Design workspace' },
        type: 'image',
        caption: 'New design workspace setup! ✨',
        isViewed: false,
        viewers: [],
        viewerCount: 234,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
      },
      {
        id: 's2',
        authorId: 'u2',
        media: { id: 'sm2', type: 'image', url: '', thumbnailUrl: '', alt: 'Coffee break' },
        type: 'image',
        caption: 'Coffee break with the team ☕',
        isViewed: false,
        viewers: [],
        viewerCount: 189,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
      },
    ],
    hasUnviewed: true,
    latestStory: {} as Story,
  },
  {
    userId: 'u7',
    stories: [
      {
        id: 's3',
        authorId: 'u7',
        media: { id: 'sm3', type: 'video', url: '', thumbnailUrl: '', alt: 'Travel vlog' },
        type: 'video',
        caption: 'Behind the scenes of today\'s shoot 🎬',
        isViewed: false,
        viewers: [],
        viewerCount: 567,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 23).toISOString(),
      },
    ],
    hasUnviewed: true,
    latestStory: {} as Story,
  },
  {
    userId: 'u4',
    stories: [
      {
        id: 's4',
        authorId: 'u4',
        media: { id: 'sm4', type: 'image', url: '', thumbnailUrl: '', alt: 'Art progress' },
        type: 'image',
        caption: 'Work in progress... coming together beautifully 🎨',
        isViewed: false,
        viewers: [],
        viewerCount: 892,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
      },
      {
        id: 's5',
        authorId: 'u4',
        media: { id: 'sm5', type: 'image', url: '', thumbnailUrl: '', alt: 'Finished piece' },
        type: 'image',
        caption: 'Finished! Swipe to see the final piece 🖼️',
        isViewed: false,
        viewers: [],
        viewerCount: 1043,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 19).toISOString(),
      },
    ],
    hasUnviewed: true,
    latestStory: {} as Story,
  },
  {
    userId: 'u9',
    stories: [
      {
        id: 's6',
        authorId: 'u9',
        media: { id: 'sm6', type: 'image', url: '', thumbnailUrl: '', alt: 'Game development' },
        type: 'image',
        caption: 'Crystal Maze - Day 180 of development 🎮',
        isViewed: true,
        viewers: [{ userId: 'u1', viewedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString() }],
        viewerCount: 345,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
      },
    ],
    hasUnviewed: false,
    latestStory: {} as Story,
  },
  {
    userId: 'u6',
    stories: [
      {
        id: 's7',
        authorId: 'u6',
        media: { id: 'sm7', type: 'image', url: '', thumbnailUrl: '', alt: 'ML visualization' },
        type: 'image',
        caption: 'Beautiful neural network visualization from today\'s research 🧠',
        isViewed: true,
        viewers: [{ userId: 'u1', viewedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() }],
        viewerCount: 456,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
        expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 16).toISOString(),
      },
    ],
    hasUnviewed: false,
    latestStory: {} as Story,
  },
]

// ============================================
// Mock Videos & Streams
// ============================================
export const mockVideos: Video[] = [
  {
    id: 'v1',
    title: 'Building a Design System from Scratch - Full Tutorial',
    description: 'In this comprehensive tutorial, we build a complete design system using Figma, covering tokens, components, and documentation.',
    authorId: 'u2',
    url: '',
    thumbnailUrl: '',
    duration: 2847,
    views: 45600,
    likes: 3420,
    dislikes: 23,
    comments: [],
    commentCount: 234,
    isLiked: false,
    isDisliked: false,
    isBookmarked: true,
    category: 'Design',
    tags: ['design system', 'figma', 'tutorial', 'ui'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'v2',
    title: 'Advanced TypeScript Patterns Every Developer Should Know',
    description: 'Deep dive into advanced TypeScript patterns including template literals, conditional types, and mapped types.',
    authorId: 'u1',
    url: '',
    thumbnailUrl: '',
    duration: 1920,
    views: 23400,
    likes: 1890,
    dislikes: 12,
    comments: [],
    commentCount: 156,
    isLiked: true,
    isDisliked: false,
    isBookmarked: false,
    category: 'Technology',
    tags: ['typescript', 'programming', 'tutorial'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'v3',
    title: 'Digital Art Process: From Sketch to Final Piece',
    description: 'Watch the complete process of creating a digital illustration from initial concept sketch to the final polished artwork.',
    authorId: 'u4',
    url: '',
    thumbnailUrl: '',
    duration: 3600,
    views: 67800,
    likes: 5670,
    dislikes: 15,
    comments: [],
    commentCount: 345,
    isLiked: false,
    isDisliked: false,
    isBookmarked: true,
    category: 'Art',
    tags: ['digital art', 'illustration', 'process', 'art'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: 'v4',
    title: 'Machine Learning in Production: Lessons Learned',
    description: 'Real-world lessons from deploying ML models at scale. Covering monitoring, drift detection, and model versioning.',
    authorId: 'u6',
    url: '',
    thumbnailUrl: '',
    duration: 2400,
    views: 18900,
    likes: 1456,
    dislikes: 8,
    comments: [],
    commentCount: 98,
    isLiked: false,
    isDisliked: false,
    isBookmarked: false,
    category: 'Technology',
    tags: ['machine learning', 'production', 'mlops'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: 'v5',
    title: 'Tashkent Street Food Tour - Hidden Gems',
    description: 'Exploring the best street food spots in Tashkent, from plov to samsa. A culinary adventure through Uzbekistan\'s capital.',
    authorId: 'u7',
    url: '',
    thumbnailUrl: '',
    duration: 1800,
    views: 123000,
    likes: 8900,
    dislikes: 45,
    comments: [],
    commentCount: 567,
    isLiked: true,
    isDisliked: false,
    isBookmarked: false,
    category: 'Lifestyle',
    tags: ['food', 'travel', 'tashkent', 'uzbekistan'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
  },
]

export const mockStreams: Stream[] = [
  {
    id: 'st1',
    title: 'Live Coding: Building a Real-time Chat App',
    description: 'Building a real-time chat application with Next.js and Socket.io from scratch. Ask questions in the chat!',
    streamerId: 'u3',
    thumbnailUrl: '',
    categoryId: 'tech',
    category: 'Technology',
    tags: ['coding', 'nextjs', 'socket.io', 'livestream'],
    viewers: 342,
    peakViewers: 456,
    isLive: true,
    isRecorded: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'st2',
    title: 'Digital Art Stream: Fantasy Character Design',
    description: 'Designing a fantasy character from scratch. Join me as I explore different styles and techniques!',
    streamerId: 'u4',
    thumbnailUrl: '',
    categoryId: 'art',
    category: 'Art',
    tags: ['art', 'digital art', 'character design', 'fantasy'],
    viewers: 1890,
    peakViewers: 2100,
    isLive: true,
    isRecorded: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'st3',
    title: 'Music Production: Lo-fi Beats Session',
    description: 'Creating chill lo-fi beats. Requests welcome in the chat! 🎵',
    streamerId: 'u7',
    thumbnailUrl: '',
    categoryId: 'music',
    category: 'Music',
    tags: ['music', 'lo-fi', 'beats', 'production'],
    viewers: 567,
    peakViewers: 678,
    isLive: true,
    isRecorded: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'st4',
    title: 'AI Research Discussion: Latest in LLMs',
    description: 'Weekly discussion on the latest developments in large language models and AI research.',
    streamerId: 'u6',
    thumbnailUrl: '',
    categoryId: 'tech',
    category: 'Technology',
    tags: ['ai', 'llm', 'research', 'machine learning'],
    viewers: 2340,
    peakViewers: 2800,
    isLive: false,
    isRecorded: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    endedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    duration: 7200,
  },
  {
    id: 'st5',
    title: 'UI/UX Design Review: Community Submissions',
    description: 'Reviewing design submissions from the community. Providing feedback and tips!',
    streamerId: 'u5',
    thumbnailUrl: '',
    categoryId: 'design',
    category: 'Design',
    tags: ['design', 'ui', 'ux', 'review'],
    viewers: 0,
    peakViewers: 1234,
    isLive: false,
    isRecorded: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endedAt: new Date(Date.now() - 1000 * 60 * 60 * 45).toISOString(),
    duration: 10800,
  },
]

// ============================================
// Mock Meetings
// ============================================
export const mockMeetings: Meeting[] = [
  {
    id: 'mt1',
    title: 'Sprint Planning - Week 18',
    description: 'Planning session for the upcoming sprint. Review backlog items and assign tasks.',
    hostId: 'u1',
    participants: [
      { userId: 'u1', role: 'host', isMuted: false, isVideoOn: true, isScreenSharing: false },
      { userId: 'u3', role: 'participant', isMuted: true, isVideoOn: false, isScreenSharing: false },
      { userId: 'u6', role: 'participant', isMuted: true, isVideoOn: true, isScreenSharing: false },
      { userId: 'u8', role: 'participant', isMuted: false, isVideoOn: false, isScreenSharing: false },
    ],
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    duration: 60,
    status: 'scheduled',
    meetingLink: 'meet/honey/sprint-18',
    type: 'video',
    isMuted: false,
    isRecording: false,
    maxParticipants: 10,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'mt2',
    title: 'Design Review: Mobile App v2',
    description: 'Review the latest designs for the mobile app version 2. Focus on the new navigation and chat interface.',
    hostId: 'u2',
    participants: [
      { userId: 'u2', role: 'host', isMuted: false, isVideoOn: true, isScreenSharing: true },
      { userId: 'u4', role: 'participant', isMuted: false, isVideoOn: true, isScreenSharing: false },
      { userId: 'u5', role: 'participant', isMuted: false, isVideoOn: true, isScreenSharing: false },
    ],
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
    duration: 45,
    status: 'scheduled',
    meetingLink: 'meet/honey/design-review',
    type: 'video',
    isMuted: false,
    isRecording: false,
    maxParticipants: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'mt3',
    title: '1:1 with Sardor - Project Update',
    description: 'Weekly sync to discuss ML pipeline improvements and data pipeline architecture.',
    hostId: 'u1',
    participants: [
      { userId: 'u1', role: 'host', isMuted: false, isVideoOn: true, isScreenSharing: false },
      { userId: 'u6', role: 'participant', isMuted: false, isVideoOn: true, isScreenSharing: false },
    ],
    scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    duration: 30,
    status: 'scheduled',
    meetingLink: 'meet/honey/1on1-sardor',
    type: 'video',
    isMuted: false,
    isRecording: false,
    maxParticipants: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
]

// ============================================
// Mock Notifications
// ============================================
export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    title: 'New Like',
    body: 'Dilnoza Rakhimova liked your post "Design System Update"',
    fromUserId: 'u2',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    actionUrl: '/feed',
  },
  {
    id: 'n2',
    type: 'comment',
    title: 'New Comment',
    body: 'Timur Aliyev commented on your post: "This is amazing work! 🚀"',
    fromUserId: 'u3',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    actionUrl: '/feed',
  },
  {
    id: 'n3',
    type: 'follow',
    title: 'New Follower',
    body: 'Yuki Tanaka started following you',
    fromUserId: 'u9',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    actionUrl: '/profile/u9',
  },
  {
    id: 'n4',
    type: 'message',
    title: 'New Message',
    body: 'Dilnoza Rakhimova sent you a message: "Want me to share the prototype?"',
    fromUserId: 'u2',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    actionUrl: '/hub',
  },
  {
    id: 'n5',
    type: 'mention',
    title: 'Mentioned You',
    body: 'Sardor Mirzayev mentioned you in Dev Team: "Great work @Jasur!"',
    fromUserId: 'u6',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    actionUrl: '/hub',
  },
  {
    id: 'n6',
    type: 'stream',
    title: 'Live Stream Started',
    body: 'Nodira Ushakova started streaming: "Digital Art Stream"',
    fromUserId: 'u4',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    actionUrl: '/streams',
  },
  {
    id: 'n7',
    type: 'meeting',
    title: 'Meeting Reminder',
    body: 'Sprint Planning - Week 18 starts in 2 hours',
    fromUserId: 'u1',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    actionUrl: '/meet',
  },
  {
    id: 'n8',
    type: 'group_invite',
    title: 'Group Invitation',
    body: 'Alex Chen invited you to join "UX Research Group"',
    fromUserId: 'u5',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    actionUrl: '/hub',
  },
  {
    id: 'n9',
    type: 'achievement',
    title: 'Achievement Unlocked! 🏆',
    body: 'You\'ve reached 10,000 followers! Congratulations on building an amazing community.',
    fromUserId: 'u1',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    actionUrl: '/profile',
  },
  {
    id: 'n10',
    type: 'like',
    title: 'Post Trending',
    body: 'Your post "Design System Update" is trending with 456 likes!',
    fromUserId: 'u1',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    actionUrl: '/feed',
  },
]

// ============================================
// Mock Files / Media
// ============================================
export const mockFiles: FileItem[] = [
  {
    id: 'f1',
    name: 'Honey_DesignSystem_v2.fig',
    type: 'document',
    size: 24576000,
    url: '',
    mimeType: 'application/x-figma',
    uploadedBy: 'u2',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    folder: 'Design',
  },
  {
    id: 'f2',
    name: 'project-proposal.pdf',
    type: 'document',
    size: 3145728,
    url: '',
    mimeType: 'application/pdf',
    uploadedBy: 'u1',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    folder: 'Documents',
  },
  {
    id: 'f3',
    name: 'team-photo-2024.jpg',
    type: 'image',
    size: 5242880,
    url: '',
    mimeType: 'image/jpeg',
    uploadedBy: 'u7',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    thumbnailUrl: '',
    width: 4000,
    height: 3000,
    folder: 'Photos',
  },
  {
    id: 'f4',
    name: 'sprint-demo-recording.mp4',
    type: 'video',
    size: 104857600,
    url: '',
    mimeType: 'video/mp4',
    uploadedBy: 'u3',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    thumbnailUrl: '',
    duration: 1800,
    folder: 'Videos',
  },
  {
    id: 'f5',
    name: 'ML-model-weights-v3.bin',
    type: 'other',
    size: 524288000,
    url: '',
    mimeType: 'application/octet-stream',
    uploadedBy: 'u6',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    folder: 'ML',
  },
  {
    id: 'f6',
    name: 'podcast-episode-12.mp3',
    type: 'audio',
    size: 52428800,
    url: '',
    mimeType: 'audio/mpeg',
    uploadedBy: 'u7',
    uploadedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    duration: 3600,
    folder: 'Audio',
  },
]

// ============================================
// Helper Functions
// ============================================
export function getUserById(id: string): User | undefined {
  return mockUsers.find((u) => u.id === id)
}

export function getChatById(id: string): Chat | undefined {
  return mockChats.find((c) => c.id === id)
}

export function getMessagesForChat(chatId: string): Message[] {
  return mockMessages.filter((m) => m.chatId === chatId)
}

export function getPostsByUser(userId: string): Post[] {
  return mockPosts.filter((p) => p.authorId === userId)
}

export function getStoriesForUser(userId: string): Story[] {
  return mockStories.find((sg) => sg.userId === userId)?.stories ?? []
}

export function getNotificationsForUser(): Notification[] {
  return mockNotifications
}
