# Generated by Django 6.0 on 2026-02-21 18:19

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='videos/covers/'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/direct/'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
