# Generated by Django 6.0 on 2026-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='group_type',
            field=models.CharField(choices=[('group', 'Group'), ('channel', 'Channel')], default='group', max_length=10),
        ),
    ]
